services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.local
    networks:
      - network

volumes:
  postgres_data:

networks:
  network: