services:
  db:
    image: postgres:18-alpine
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env.local
    networks:
      - network

  redis:
    image: redis:alpine
    ports:
      - "63791:6379"
    volumes:
      - redis_data:/data
    networks:
      - network

  redis-matchmaking:
    image: redis:alpine
    ports:
      - "63792:6379"
    volumes:
      - redis_matchmaking_data:/data
    networks:
      - network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "56721:5672"
      - "15672:15672"
    networks:
      - network

volumes:
  postgres_data:
  redis_data:
  redis_matchmaking_data:

networks:
  network: